// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Core.Models;

[Table("employee", Schema = "employees")]
public partial class Employee
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("birth_date")]
    public DateOnly BirthDate { get; set; }

    [Column("first_name")]
    [StringLength(14)]
    public string FirstName { get; set; } = null!;

    [Column("last_name")]
    [StringLength(16)]
    public string LastName { get; set; } = null!;

    [Column("hire_date")]
    public DateOnly HireDate { get; set; }
}